# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5abee655b7f804f2ef119647c2ccb5d186716b5b9ab43388e395d6d295a187b0cda1e8e171043bd1ab70da6417ef0c4d27333f0f7c7f21febecce1198c05b453

test:
  secret_key_base: 46c56004213451e86bedff7f6018a8ab73c8bf2be33c714d229580df6352d420ac6631457ef01ff553c9631cd81a6e74c08fda7774ebe117171e0a7a2496d5d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
